app_name: "FraudDetectionStreamApp"
master: "local[*]"

spark_config:
  spark.sql.shuffle.partitions: 2
  spark.default.parallelism: 2
  spark.streaming.backpressure.enabled: true
  spark.streaming.kafka.maxRatePerPartition: 50
  spark.sql.streaming.trigger.interval: "10 seconds"
  spark.sql.streaming.checkpointLocation: "checkpoints"